<a href="https://colab.research.google.com/github/Santosh-16k/Learn-PyTorch/blob/master/60_minute_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required modules

In [0]:
import torch
import torchvision

Creating an empty tensor

In [25]:
x = torch.empty(5,3)
print(x)

tensor([[4.4678e-01, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 2.2136e+20],
        [4.1731e+21, 4.3249e-05, 2.0920e+23],
        [4.1763e+21, 2.6080e-09, 1.0579e+21],
        [4.3437e-05, 1.3400e-08, 2.0674e+22]])


Creating a randomly initialized matrix

In [26]:
x = torch.rand(5,3)
print(x)

tensor([[0.3349, 0.1229, 0.0335],
        [0.0549, 0.3773, 0.7390],
        [0.5463, 0.0443, 0.4052],
        [0.4377, 0.2410, 0.6738],
        [0.6720, 0.2400, 0.5273]])


Creating a matrix filled with zeros with a specific data type (dtype) *long*

In [27]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Creating a tensor from data

In [28]:
x = torch.tensor([2, 3.5, 9])
print(x)

tensor([2.0000, 3.5000, 9.0000])


Create tensor based on existing tensor

In [29]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3305,  0.4689,  0.8419],
        [ 0.7282,  0.1106,  0.8578],
        [-0.2218, -0.7418, -1.8063],
        [ 1.5172,  1.5195, -0.7481],
        [-0.3181, -1.5961,  0.0090]])


Obtain tensor size

In [30]:
print(x.size())

torch.Size([5, 3])


# Operations

Addition

In [31]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.7555,  1.4271,  1.3042],
        [ 0.7322,  0.9548,  1.5212],
        [ 0.6084,  0.2486, -1.4500],
        [ 1.7827,  2.2453, -0.2774],
        [ 0.1281, -0.9357,  0.4188]])


Or another syntax for addition

In [32]:
print(torch.add(x, y))

tensor([[ 0.7555,  1.4271,  1.3042],
        [ 0.7322,  0.9548,  1.5212],
        [ 0.6084,  0.2486, -1.4500],
        [ 1.7827,  2.2453, -0.2774],
        [ 0.1281, -0.9357,  0.4188]])


If you need output in a variable

In [33]:
result = torch.empty(5, 3)
torch.add(x,y, out=result)
print(result)

tensor([[ 0.7555,  1.4271,  1.3042],
        [ 0.7322,  0.9548,  1.5212],
        [ 0.6084,  0.2486, -1.4500],
        [ 1.7827,  2.2453, -0.2774],
        [ 0.1281, -0.9357,  0.4188]])


For inplace addition

In [34]:
y.add_(x)
print(y)

tensor([[ 0.7555,  1.4271,  1.3042],
        [ 0.7322,  0.9548,  1.5212],
        [ 0.6084,  0.2486, -1.4500],
        [ 1.7827,  2.2453, -0.2774],
        [ 0.1281, -0.9357,  0.4188]])


Resize a tensor

In [35]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Use `.item()` for a single element tensor to get value as python number

In [36]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4693])
0.46930786967277527


# NumPy Bridge

Even after conversion from torch tensor to numpy, the data is shared. Changing one will change the other

In [37]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [38]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [39]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting from numpy array to torch tensor

In [40]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensor

Use `.to()` function to move data to any device

In [41]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

tensor([1.4693], device='cuda:0')
tensor([1.4693], dtype=torch.float64)
